### PR TITLE
Adds linter file

### PR DESCRIPTION
**Pull request by MrSayyod**
Hello,

We are making a pull request for the Micro-Reddit project, which required us to create the models and associations for a forum application like Reddit. It allows users to make posts and comments. 

There were some errors by Rubocop which arose because the local repository was not connected to the remote repository before Rubocop was added. As a result, Github keeps finding a Rubocop error even though there are no errors locally. 

We worked with the remote repository which keeps referencing a previous structure in our project and not the updated structure. This is why it keeps giving the Rubocop error even though there are no errors to be found locally. 

We will ensure that this type of error is avoided in future projects by connecting to the remote repository at the appropriate stage of development. Our future projects will not contain these types of errors. 

Thank you for your time and review.

### CODE REVIEW

**Review by shshamim63 — CHANGES_REQUESTED** [review]
## Status :1234:  Changes Required 
___
Hi @MrSayyod and @Calvinoea :wave: 
you generated the migrations and associations properly. The root readme loots descriptive. But the linter is blocking me. I think you are executing the rubocop by using the inner rubocop.yml of micro-reddit. That is why you are not getting errors locally. But the workflow is running the root rubocop.yml. Which is informing total 131 offenses. So you have to fix it.
image (1)
___
###### Process to fix it.
___
Please do the following changes.
#### remove the following files indise micro-redit
- README.md
- .rubocop.yml
#### remove the following files from the root directory
- Gemfile
- Gemfile.lock
- .gitignore

**After performing all the following tasks, move all the files and folders inside micro-reddit to root directory.**
___
Now your linter will check the root rubocop.yml properly.
___
###### Please do the following changes and send another review request. And if you find anything confusing, don't hesitate to knock me.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

**Comment by Calvinoea** [comment]
> ## Status 🔢 Changes Required
> Hi @MrSayyod and @Calvinoea 👋
> you generated the migrations and associations properly. The root readme loots descriptive. But the linter is blocking me. I think you are executing the rubocop by using the inner rubocop.yml of micro-reddit. That is why you are not getting errors locally. But the workflow is running the root rubocop.yml. Which is informing total 131 offenses. So you have to fix it.
> image (1)
> 
> ###### Process to fix it.
> Please do the following changes.
> 
> #### remove the following files indise micro-redit
> * README.md
> * .rubocop.yml
> 
> #### remove the following files from the root directory
> * Gemfile
> * Gemfile.lock
> * .gitignore
> 
> **After performing all the following tasks, move all the files and folders inside micro-reddit to root directory.**
> 
> Now your linter will check the root rubocop.yml properly.
> 
> ###### Please do the following changes and send another review request. And if you find anything confusing, don't hesitate to knock me.
> ## 🌿 Happy Coding 🌿
> ### Shakhawat Hossain

Thank you for your review @shshamim63 . The changes have been made and all checks have passed.

**Review by Torres-ssf — APPROVED** [review]
### Project Approved :+1: 
Hi there team
Great work on this project :clap: 
And good luck in the next one

Happy coding :computer: 
**Sergio Torres**

**Comment by Calvinoea** [comment]
> ### Project Approved 👍
> Hi there team
> Great work on this project 👏
> And good luck in the next one
> 
> Happy coding 💻
> **Sergio Torres**

Thank you @Torres-ssf !

**Pull request merged**
